// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/login" | "/admin/rate-limit" | "/admin/user" | "/aml-policy" | "/car-rental" | "/concierge-service" | "/debit-cards" | "/exchange" | "/login" | "/profile" | "/register" | "/request-reset" | "/reset-password"
type AppRouteHandlerRoutes = "/api/admin/kyc/approve" | "/api/admin/kyc/pending" | "/api/admin/kyc/reject" | "/api/admin/kyc/user" | "/api/admin/rate-limit-stats" | "/api/auth/change-password" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/register" | "/api/auth/verify"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/login": {}
  "/admin/rate-limit": {}
  "/admin/user": {}
  "/aml-policy": {}
  "/api/admin/kyc/approve": {}
  "/api/admin/kyc/pending": {}
  "/api/admin/kyc/reject": {}
  "/api/admin/kyc/user": {}
  "/api/admin/rate-limit-stats": {}
  "/api/auth/change-password": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/register": {}
  "/api/auth/verify": {}
  "/car-rental": {}
  "/concierge-service": {}
  "/debit-cards": {}
  "/exchange": {}
  "/login": {}
  "/profile": {}
  "/register": {}
  "/request-reset": {}
  "/reset-password": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
